name = "HugoBalticTheme"
license = "MIT"
licenselink = "https://github.com/baltic-security/HugoBalticTheme/blob/master/LICENSE"
description = "A fork of the devcows Hugo Universal Theme"
homepage = "https://github.com/baltic-security/HugoBalticTheme"
#tags = ["blog", "company", "portfolio", "projects", "minimal", "responsive"]
#features = ["blog", "themes", "disqus", "minimal", "responsive"]
min_version = 0.15

[author]
    name = "BFS"
    homepage = "https://github.com/baltic-security"

# If Porting existing theme
[original]
    author = "devcows"
    homepage = "https://github.com/devcows"
